In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [3]:
def sigmoid_derivative(x):
    s=sigmoid(x)
    return s * (1-s)

In [4]:
def tanh(x):
    return np.tanh(x)

In [6]:
def tanh_derivative(x):
    return 1-(np.tanh(x)*np.tanh(x))

In [16]:
class LSTMCell:
    def __init__(self, input_dim, hidden_dim):
        self.hidden_dim = hidden_dim
        self.concat_dim = input_dim + hidden_dim
        self.W_f=np.random.randn(hidden_dim,self.concat_dim) * 0.1
        self.b_f = np.zeros((hidden_dim, 1))
        self.W_i=np.random.randn(hidden_dim,self.concat_dim) * 0.1
        self.b_i = np.zeros((hidden_dim, 1))
        self.W_c=np.random.randn(hidden_dim,self.concat_dim) * 0.1
        self.b_c = np.zeros((hidden_dim, 1))
        self.W_o=np.random.randn(hidden_dim,self.concat_dim) * 0.1
        self.b_o = np.zeros((hidden_dim, 1))
    
    def forward(self,x_t, h_prev, C_prev):
        z = np.vstack((h_prev, x_t))
        
        f_t = sigmoid(np.dot(self.W_f,z) + self.b_f)
        i_t = sigmoid(np.dot(self.W_i,z) + self.b_i)
        c_tilde = tanh(np.dot(self.W_c,z) + self.b_c)
        o_t = sigmoid(np.dot(self.W_o,z) + self.b_o)
        
        C_t = (f_t * C_prev) + (i_t * c_tilde)
        h_t = o_t * tanh(C_t)
        
        return h_t, C_t
        
    def forward_sequence(self, X):
        h_t = np.zeros((self.hidden_dim, 1))
        C_t = np.zeros((self.hidden_dim, 1))
        
        hidden_states = []
        
        for i in range(X.shape[1]):
            h_t, C_t = self.forward(X[:, i].reshape(-1,1), h_t, C_t)
            hidden_states.append(h_t)
        
        return np.hstack(hidden_states)
                        
        
    
        
        
        
        
    

In [17]:
# --- Verification Test Drive ---
if __name__ == "__main__":
    # 1. Define network parameters
    INPUT_FEATURES = 3   # e.g., three input channels/features per timestep
    HIDDEN_MEMORY = 4    # e.g., the cell tracks 4 internal states
    SEQUENCE_LENGTH = 5  # e.g., a sequence tracking 5 consecutive timesteps
    
    print("Initializing LSTM cell...")
    lstm = LSTMCell(input_dim=INPUT_FEATURES, hidden_dim=HIDDEN_MEMORY)
    
    # 2. Generate synthetic data matrix of shape (input_dim, sequence_length)
    # This generates random floating numbers from a normal distribution
    synthetic_data = np.random.randn(INPUT_FEATURES, SEQUENCE_LENGTH)
    
    print("\n--- Input Data ---")
    print(f"Synthetic Input Shape: {synthetic_data.shape} (Features, Timesteps)")
    print("Raw Input Array:")
    print(synthetic_data)
    
    # 3. Run the sequence pass
    print("\nProcessing full sequence through LSTM layer...")
    output_history = lstm.forward_sequence(synthetic_data)
    
    print("\n--- Output Results ---")
    print(f"Output Matrix Shape: {output_history.shape} (Hidden Units, Timesteps)")
    print("Resulting Hidden States across time:")
    print(output_history)

Initializing LSTM cell...

--- Input Data ---
Synthetic Input Shape: (3, 5) (Features, Timesteps)
Raw Input Array:
[[ 1.25386203 -0.62528567 -0.55926347 -0.87201094 -1.56435281]
 [ 1.92863102 -1.52104615  1.02839603 -0.06035626  1.20422386]
 [-0.19050026 -0.36411609 -2.03515207 -0.38227219  1.03283373]]

Processing full sequence through LSTM layer...

--- Output Results ---
Output Matrix Shape: (4, 5) (Hidden Units, Timesteps)
Resulting Hidden States across time:
[[0.43733839 0.32790506 0.29517664 0.22792122 0.16726966]
 [0.39113507 0.32936051 0.27076035 0.25064802 0.19777405]
 [0.52297638 0.20897213 0.23200236 0.19167368 0.20025024]
 [0.45659838 0.25685079 0.26740898 0.22714039 0.22377156]]
